rvm:
  - 3.0.0
  - 2.7.2
  - 2.5.8

gemfile:
  - gemfiles/rails61.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails42.gemfile

matrix:
  exclude:
    - rvm: 3.0.0
      gemfile: gemfiles/rails52.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/rails42.gemfile

script: bundle exec rspec spec

addons:
  postgresql: "9.4"
