rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9

gemfile:
  - gemfiles/rails60.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails42.gemfile

script: bundle exec rspec spec

addons:
  postgresql: "9.4"
